# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

title: Trung's Blog
email: nqt.quoctrung94@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Trung's Blog on Exploring Data and Mastering CP Algorithms.
baseurl: "/my-blog" 
url: "https://nqtquoctrung94.github.io"

author: Quoc-Trung Nguyen

# twitter_username: jekyllrb
github_username:  nqtquoctrung94

# theme: minima
plugins:
  - jekyll-feed

#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
